### ISSUE TITLE
403 CORS error when using `refresh-token` endpoint

### ISSUE THREAD

**Issue by migoox** [Java-DZGS/ingreedio#58]
**Background**: When api call gets 401 error, the axios interceptor tries to use `refresh-token` endpoint to refresh the access token and retry the call with the new token.
**The problem**: When axios tries to use `refresh-token` endpoint there is 403 Forbidden response related to 'Cross-Origin Request Blocked` on our remote.

![image](https://github.com/Java-DZGS/ingreedio/assets/56317134/ee957f9e-55d4-4e76-8200-271ac0f36578)

![image](https://github.com/Java-DZGS/ingreedio/assets/56317134/5eb87b3f-245b-4009-846a-b3a82e54b16e)

**Browser**: Firefox

**Comment by mslup** [comment]
Accessing `/api/ingredients/{id}/likes` also returned a CORS error for me. 

![image](https://github.com/Java-DZGS/ingreedio/assets/132074948/da520f5c-396a-471d-8a6b-cc1823bdb4f4)

**Comment by kubazuch** [comment]
I think @mslup should investigate this as CORS author

**Comment by mslup** [comment]
Yes that's why I assigned myself to this issue :3

**Comment by kubazuch** [comment]
That's superb! Keep up your work!

**Comment by mslup** [comment]
Solution: use endpoints that exist :-)
