### ISSUE TITLE
Update frontend after backend `Product` domain refactor

### ISSUE THREAD

**Issue by kubazuch** [Java-DZGS/ingreedio#89]
@migoox please state all changes you've done in https://github.com/Java-DZGS/ingreedio-api/pull/135 which have to be addressed here.

**Comment by migoox** [comment]
# Products domain endpoints changes
## Products search endpoint
Renamed `GET /api/products` ->  `GET /api/products/search`

Provider/brand are now objects.
New response example: 

```json
{
  "id": 0,
  "name": "string",
  "largeImageUrl": "string",
  "provider": {
    "id": 0,
    "name": "string"
  },
  "brand": {
    "id": 0,
    "name": "string"
  },
  "longDescription": "string",
  "volume": "string",
  "isLiked": true,
  "rating": 0
}
```

## Get product endpoint
Provider/brand/category/ingredient are now objects.

New response example:

```json
{
  "id": 0,
  "name": "string",
  "largeImageUrl": "string",
  "provider": {
    "id": 0,
    "name": "string"
  },
  "brand": {
    "id": 0,
    "name": "string"
  },
  "categories": [
    {
      "id": 0,
      "name": "string"
    }
  ],
  "longDescription": "string",
  "volume": "string",
  "ingredients": [
    {
      "id": 0,
      "name": "string"
    }
  ],
  "isLiked": true,
  "rating": 0
}
```
## POST/PUT/PATCH product
These endpoints requires ids of brand/provider/category/ingredient (before it required names).

Example request body:
```json
{
  "name": "string",
  "smallImageUrl": "string",
  "largeImageUrl": "string",
  "provider": 0,
  "brand": 0,
  "categories": [
    0
  ],
  "shortDescription": "string",
  "longDescription": "string",
  "volume": "string",
  "ingredients": [
    0
  ]
}
```
## New endpoints
- products patch: `PATCH /api/products/{id}`
