### ISSUE TITLE
Login and registartion integration with backend

### ISSUE THREAD

**Issue by mslup** [Java-DZGS/ingreedio#9]
Requires backend login and registration to be set up

- integration with backend

**Comment by kubazuch** [comment]
Depends on #5 and #26

**Comment by andrmdmd** [comment]
When registration fields will be specified, they should be added as input fields (using custom Input component) to the Registration page. Login page formatting should not require changes (unless login will not be done by email - then type and naming of the input field should be corrected).

Frontend architecture expects api calls to be made using epics (https://redux-observable.js.org/docs/basics/Epics.html). Please consider this while working on this task.
